name: in5550_exam

channels:
- conda-forge
- defaults

dependencies:
- python>=3.7
- pip>=20.0.2
- argparse
- dataclasses
- gensim>=3.8.1
- matplotlib>=3.1.3
- numpy>=1.18.1
- pandas>=1.0.3
- pickle
- scikit-learn>=0.22.1
- scipy>=1.4.1
- tensorflow>=2.1.0